#!/bin/bash -e
export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-3.0.3.778-linux
export PATH=$SONAR_SCANNER_HOME/bin:$PATH
export SONAR_BUILD_WRAPPER=$HOME/.sonar/build-wrapper-linux-x86
export PATH=$SONAR_BUILD_WRAPPER:$PATH

mkdir -p "$HOME"/.local/share

mkdir build
cd build
export TZ="America/Los_Angeles"

if [[ "$BUILDTYPE" == "cmake-make" ]]; then
	echo Path is $PATH
	cmake ../gnucash
	../sonarqube
	build-wrapper-linux-x86-64 --out-dir bw-outputs make -j 4 VERBOSE=1;
	sonar-scanner -Dsonar.projectKey=gnucash-fit:gnucash-fit -Dsonar.sources=../ -Dsonar.cfamily.build-wrapper-output=bw-output -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=fit-swe -Dsonar.login=$SONARQUBE_API_TOKEN
	make check || ../afterfailure
elif [[ "$BUILDTYPE" == "cmake-ninja" ]]; then
    cmake ../gnucash -DWITH_PYTHON=ON -DCMAKE_BUILD_TYPE=debug -G Ninja
    ninja
    ninja check || ../afterfailure;
elif [[ "$BUILDTYPE" == "autotools" ]]; then
    ../gnucash/autogen.sh;
    ../gnucash/configure --enable-python
    make;
    make check || ../afterfailure
else
    echo "Unknown buildtype: \"$BUILDTYPE\". Not building."
fi
