#!/bin/bash -e

# Install SonarQube on travis. 

# Install sonar-scanner
export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-3.0.3.778-linux
rm -rf $SONAR_SCANNER_HOME
mkdir -p $SONAR_SCANNER_HOME
curl -sSLo $HOME/.sonar/sonar-scanner.zip https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.0.3.778-linux.zip
unzip $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
rm $HOME/.sonar/sonar-scanner.zip
export PATH=$SONAR_SCANNER_HOME/bin:$PATH
export SONAR_SCANNER_OPTS="-server"

# Install build wrapper
export SONAR_BUILD_WRAPPER=$HOME/.sonar/build-wrapper-linux-x86
rm -rf $SONAR_BUILD_WRAPPER
mkdir -p $SONAR_BUILD_WRAPPER
curl -sSLo $HOME/.sonar/build-wrapper-linux-x86.zip https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
unzip $HOME/.sonar/build-wrapper-linux-x86.zip -d $HOME/.sonar/
rm $HOME/.sonar/build-wrapper-linux-x86.zip
export PATH=$SONAR_BUILD_WRAPPER:$PATH